/**
 * Image registry.
 *
 * Every photograph on the site is declared here once, with the widths it is
 * available in, so the <Picture> primitive can emit a correct `srcset` instead of
 * shipping one oversized file to every device. The original build served a single
 * 1920px JPEG to phones.
 *
 * ── Remote vs local ────────────────────────────────────────────────────────────
 * Four photographs are still served from images.pexels.com. Self-hosting them is
 * better on two counts: it removes a third-party request that transmits every
 * visitor's IP address (a DSGVO matter, currently declared in the
 * Datenschutzerklärung) and it removes a DNS + TLS hop from the LCP path.
 *
 * The download was not possible from the build environment this was developed in
 * (network policy blocked images.pexels.com), so they remain remote for now, with
 * responsive `srcset` built from Pexels' own `?w=` parameter — the sizing win
 * applies either way.
 *
 * To finish the job on a machine with open network access:
 *   1. npm run assets:fetch     — downloads the four originals to assets-src/
 *   2. npm run assets           — generates AVIF/WebP variants into public/img/
 *   3. set USE_LOCAL_PHOTOS below to `true`
 * No component changes are needed.
 */

export const USE_LOCAL_PHOTOS = false;

export interface ImageSource {
  /** Identifier, also the filename stem under public/img when self-hosted. */
  id: string;
  /** Remote origin, used until the photograph is self-hosted. */
  remote: string;
  /** Widths to offer in the srcset. */
  widths: number[];
  /** Intrinsic aspect ratio (w / h), for reserving space where no fixed-height container exists. */
  aspect: number;
}

const PEXELS_WIDTHS = [640, 960, 1280, 1600, 1920, 2400];

export const photos = {
  hero: {
    id: 'hero',
    remote: 'https://images.pexels.com/photos/830891/pexels-photo-830891.jpeg',
    widths: PEXELS_WIDTHS,
    aspect: 3 / 2,
  },
  problemTexture: {
    id: 'problem-texture',
    remote: 'https://images.pexels.com/photos/466685/pexels-photo-466685.jpeg',
    widths: [960, 1280, 1920],
    aspect: 3 / 2,
  },
  contactTexture: {
    id: 'contact-texture',
    remote: 'https://images.pexels.com/photos/3184291/pexels-photo-3184291.jpeg',
    widths: [960, 1280, 1920],
    aspect: 3 / 2,
  },
  finalCta: {
    id: 'final-cta',
    remote: 'https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg',
    widths: [640, 960, 1280, 1600, 1920],
    aspect: 3 / 2,
  },
} satisfies Record<string, ImageSource>;

export type PhotoKey = keyof typeof photos;

/** A single Pexels URL at a given width. */
function pexelsUrl(base: string, width: number) {
  return `${base}?auto=compress&cs=tinysrgb&w=${width}`;
}

/** Path to a locally generated variant. */
function localUrl(id: string, width: number, ext: 'avif' | 'webp' | 'jpg') {
  return `/img/${id}-${width}.${ext}`;
}

export interface ResolvedImage {
  src: string;
  srcSet: string;
  /** AVIF/WebP sources, empty while the photograph is still remote. */
  sources: { type: string; srcSet: string }[];
  aspect: number;
}

/** Builds the `src`, `srcset` and modern-format `<source>` list for a photograph. */
export function resolvePhoto(key: PhotoKey): ResolvedImage {
  const photo = photos[key];
  const fallbackWidth = photo.widths[Math.floor(photo.widths.length / 2)];

  if (!USE_LOCAL_PHOTOS) {
    return {
      src: pexelsUrl(photo.remote, fallbackWidth),
      srcSet: photo.widths.map((w) => `${pexelsUrl(photo.remote, w)} ${w}w`).join(', '),
      sources: [],
      aspect: photo.aspect,
    };
  }

  return {
    src: localUrl(photo.id, fallbackWidth, 'jpg'),
    srcSet: photo.widths.map((w) => `${localUrl(photo.id, w, 'jpg')} ${w}w`).join(', '),
    sources: [
      {
        type: 'image/avif',
        srcSet: photo.widths.map((w) => `${localUrl(photo.id, w, 'avif')} ${w}w`).join(', '),
      },
      {
        type: 'image/webp',
        srcSet: photo.widths.map((w) => `${localUrl(photo.id, w, 'webp')} ${w}w`).join(', '),
      },
    ],
    aspect: photo.aspect,
  };
}

/**
 * Locally processed images (generated by `npm run assets` from src/Images).
 * These are always self-hosted.
 */
export const localImages = {
  portrait: { id: 'cedrik', widths: [480, 720, 960], aspect: 3 / 4 },
} as const;

/** Testimonial avatars, generated at 96 and 192 (2× for retina). */
export function resolveAvatar(id: string): ResolvedImage {
  const widths = [96, 192];
  return {
    src: localUrl(id, 96, 'jpg'),
    srcSet: widths.map((w) => `${localUrl(id, w, 'jpg')} ${w}w`).join(', '),
    sources: [
      {
        type: 'image/avif',
        srcSet: widths.map((w) => `${localUrl(id, w, 'avif')} ${w}w`).join(', '),
      },
      {
        type: 'image/webp',
        srcSet: widths.map((w) => `${localUrl(id, w, 'webp')} ${w}w`).join(', '),
      },
    ],
    aspect: 1,
  };
}

export function resolveLocal(key: keyof typeof localImages): ResolvedImage {
  const image = localImages[key];
  const fallbackWidth = image.widths[image.widths.length - 1];
  return {
    src: localUrl(image.id, fallbackWidth, 'jpg'),
    srcSet: image.widths.map((w) => `${localUrl(image.id, w, 'jpg')} ${w}w`).join(', '),
    sources: [
      {
        type: 'image/avif',
        srcSet: image.widths.map((w) => `${localUrl(image.id, w, 'avif')} ${w}w`).join(', '),
      },
      {
        type: 'image/webp',
        srcSet: image.widths.map((w) => `${localUrl(image.id, w, 'webp')} ${w}w`).join(', '),
      },
    ],
    aspect: image.aspect,
  };
}
